---
name: Johan Ibrahim M.D
position: "Clinical Research Associate | Real World Data Specialist | Statistician"
address: "Bandar Baru Bangi, Selangor, Malaysia"
phone: "+6012 6466545"
#www: samabbott.co.uk
profilepic: 
email: johan@ms.pmc.edu.my
twitter: DrJohan81
github: DrJohan
linkedin: Johan Ibrahim
skype: live:salterharris_1
aboutme: "A dedicated, highly motivated and enthusiastic medical graduate with in-depth knowledge of research design and methodologies, medical statistic, big data capture, curation, manipulation and visualization and has been certified Good Clinical Practice researcher from National Institute of Health (NIH) Malaysia. I also have an excellent and vast exposure into research since undergraduate from pure clinical to community research setting. I have a vision that the world will become a better place for a living using research as a tool.."
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 009ACD
output: vitae::awesomecv
header-includes:
  \usepackage{multicol}
  \usepackage{colortbl}
  \arrayrulecolor{white}
  \usepackage{hhline}
  \definecolor{light-gray}{gray}{0.95}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
source("../scripts/install.R")
```
\faIcon{plane} My journey
============================

```{r edu_plot,fig.align='center', fig.width=6.5, fig.height=3, fig.showtext=TRUE}
load.fontawesome()
uni <- fontawesome('fa-university')
work <- fontawesome('fa-briefcase')
# teach <- fontawesome('fa-chalkboard')

world <- getMap(resolution = "high")
world <- world %>% st_as_sf()
cities <- st_sfc(
    st_point(c(-79.00453,-2.90055)),
    st_point(c(-9.13333,38.71667)),
    st_point(c(7.6261,51.9607)),
    st_point(c(12.9864,47.8029))
  ) %>%
  st_sf(name = c('Cuenca, EC','Lisbon, PT','Münster, DE', 'Salzburg, AT')) %>%
  st_set_crs(4326) %>%
  mutate(label = c(paste(work,uni, sep = " "), rep(uni,2), work))

routes <- cities %>%
  points2line() %>%
  slice(c(2,7,12)) %>%
  st_segmentize(units::set_units(100, m))

ggplot(data = world) +
  geom_sf(color = 'white', lwd = 0.1) +
  xlab("") + ylab("") +
  geom_sf_text(
    data = cities,
    aes(label = label),
    size = 3,
    color = '#009ACD',
    family = "fontawesome-webfont"
  ) +
  geom_sf(
    data = routes, color = '#009ACD', size = 0.5, alpha = 0.5, linetype = 'dotted'
  ) +
  coord_sf(crs = '+proj=robin', xlim = c(-10000000, 4500000), ylim = c(-390000,6100000)) +
  theme_minimal() +
  theme(
    panel.grid = element_line(color = 'transparent'),
    plot.margin = margin(-1, 0, -1, 0, "cm"),
    axis.text = element_blank(),
    axis.title = element_blank()
  )
```

```{r get data, include=FALSE}
## Education
edu <- read_csv(here("data", "education.csv"))

## Jobs
jobs <- read_csv(here::here("data", "jobs.csv"))

## Software
software <- read_csv(here::here("data", "software.csv")) %>% 
  arrange(desc(when)) 

## Dashboards
dashboards <- read_csv(here::here("data", "dashboards.csv")) %>% 
  arrange(desc(when)) 

## Teaching
teaching <- read_csv(here::here("data", "teaching.csv")) %>% 
  arrange(desc(when))

## Presentations
presentations <- read_csv(here::here("data", "presentations.csv")) %>% 
  arrange(desc(when))

## Training
training <- read_csv(here::here("data", "training.csv")) %>% 
  arrange(desc(end))

## Skills
skills <- read_csv(here::here("data", "skills.csv")) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup %>% 
  unique

## Service
service <- read_csv(here::here("data", "service.csv"))
```

\faIcon{university} Education
==================================
```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni,
                 why = details)

```

\faIcon{briefcase} Professional Experience
============================================

```{r research}
jobs %>% 
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details)
```
\faIcon{brain} Skills
================================
<!-- \noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}} -->

<!-- \par\noindent\nobreak\vspace{-30pt}\rule{\textwidth}{1pt} -->

```{r}
skills %>% 
  detailed_entries(what = skill, with = category)
```
\pagebreak

# Training

```{r}
training %>% 
  detailed_entries(what = what, with = with, when = when, where = where, why = why)
```



\pagebreak

# Selected Software

**`R` Packages**

```{r}
software %>% 
  detailed_entries(what = what, with = package, when = when, where = where, why = why)
```

**Interactive tools**

```{r}
dashboards %>% 
  dplyr::mutate(with = what, 
                what = why) %>% 
  detailed_entries(what = what, with = with, when = when, where = where)
```

*See [my GitHub](https://github.com/seabbs/) for a complete overview of my software both released and in development.*

# Presentations

```{r}
presentations %>% 
  detailed_entries(what = what,
                   when = when,
                   with = with,
                   where = where,
                   why = why,
                   .protect = TRUE)
```

# Service

```{r}
service %>% 
  detailed_entries(with = type, why = details)
```
